.Dd August 8, 2022
.Dt XCPICK 1
.Sh NAME
.Nm xcpick
.Nd simple color picker for X
.Sh SYNOPSIS
.Nm
.Op Fl hHv
.Op Fl p Ar prefix
.Sh DESCRIPTION
The
.Nm
application lets you pick any color from the screen.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl H
set prefix to the hash symbol (same as -p '#')
.It Fl v
display the program version
.It Fl p
set output prefix
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It copy the selected color to the clipboard
xcpick | xclip -i -sel clipboard
.It show a notification on the screen with the selected color
xcpick | xargs -I{} notify-send 'xcpick' '{}'
.It see much bigger preview of the selected color
xcpick -H | xranco -l /dev/stdin
.It print selected color prefixed with 0x
xcpick -p 0x
.El
.Sh EXIT STATUS
.Bl -tag -width indent
.It 0
a color has been picked
.It 1
an error occurred
.It 2
no color has been picked
.El
.Sh SEE ALSO
.Xr X 7
.Xr xranco 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xcpick/issues
